server:
  port: 8085
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
    spring.h2.console.settings.web-allow-others: false	  	

  datasource:
    url: jdbc:h2:mem:company
    username: sa
    password:
    driverClassName: org.h2.Driver
  
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show_sql: true
    hibernate:
     ddl-auto: update
 
  
  application:
    name: 'company'
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  cloud:
    config:
      server:
        git:
          uri: 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka